version: '3.8'

services:
  app:
    image: book000/bluemap-generator
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    entrypoint: java -jar /app/cli.jar
    init: true
