version: '3.8'

services:
  app:
    image: book000/bluemap-generator
    volumes:
      - type: bind
        source: ./world
        target: /app/world
        read_only: true
      - type: bind
        source: ./web
        target: /app/web
      - type: bind
        source: ./config
        target: /app/config
        read_only: true
    init: true
